# Generated by Django 6.0 on 2025-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_id', models.BigIntegerField(unique=True)),
                ('role', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('intern_type', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('perks', models.TextField()),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
